function PasonData = PasonImport(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PasonData = PasonImport(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  PasonData = PasonImport(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  PasonData = PasonImport("..\GRP_Public\Well 2 SLB Trials 1-8-2020\Well 2 Flow Trial 2 SLB 1-8-2020.txt", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Jan-2020 00:00:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["DATE", "TIME", "WELL1TUBING", "Tank1", "Strokes2", "Casing", "Separator", "ATPUMP2", "CORETECUPSTREAM", "CORIOLISFLOW", "Tank2", "Tank3", "Tank4"];
opts.VariableTypes = ["datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, 2, "InputFormat", "HH:mm:ss");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PasonData = readtable(filename, opts);

end