function PTGaugeData = PTGaugeImport(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  PTGaugeData = PTGaugeImport(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  PTGaugeData = PTGaugeImport(FILE, SHEET) reads from the specified
%  worksheet.
%
%  PTGaugeData = PTGaugeImport(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  LSUGaugePT487 = importfile("..\GRP_Public\LSU_Gas_Kick_Test_DTS_Gauge_Data_Day1-3_Jan8-10_2020\LSU_Gauge_PT_Data\LSU_Gauge_PT_487.35_ftMD_Jan8-10_2020.xlsx", "ESOI(020030)_2020_01_08", [2, 55106]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Jan-2020 00:19:03

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, inf];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["TimeStamp", "BankDataPressurePTPressureApsi", "BankDataTemperaturePTTemperatureAC"];
opts.SelectedVariableNames = ["TimeStamp", "BankDataPressurePTPressureApsi", "BankDataTemperaturePTTemperatureAC"];
opts.VariableTypes = ["datetime", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "");

% Import the data
PTGaugeData = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    PTGaugeData = [PTGaugeData; tb]; %#ok<AGROW>
end

end